url: https://tirisfal.wtf
baseurl: ''
timezone: Europe/Paris
name: Гильдия Совет Тирифсаля
brand: Совет Тирисфаля
description: Гильдия Совет Тирисфаля @ EU Ревущий Фьорд, World of Warcraft
icon: /assets/img/icon
logo: /assets/img/sovet
raider:
  region: eu
  realm: howling-fjord
  name: Совет Тирисфаля

verification:
  yandex: 25d6f61698f4028c
  google: ''

markdown: kramdown
sass:
    style: compressed

compress_html:
  ignore:
    envs: ['local']
  clippings: all
  comments: all
  startings: all
  endings: all
  blanklines: false
  profile: false

keep_files:
- CNAME
- assets
- favicon.ico

exclude:
- .git
- .github
- .gitignore
- .gitlab-ci.yml
- tags
- vendor
- Gemfile
- Gemfile.lock
- Makefile
- README.md
